### ISSUE TITLE
Post a screenshot in your readme.....

### ISSUE THREAD

**Issue by PySimpleGUI** [xxenoss/Todo-app#1]
> Interested in knowing the noob coder????

![image](https://user-images.githubusercontent.com/46163555/222925419-71c7d958-a4ee-4489-a3ab-afa6830af297.png)

Sure!

Where you've got that `(X)` in your readme, drop in a screenshot.

You can add it by pasting a screenshot into an issue, like this:

![image](https://user-images.githubusercontent.com/46163555/222925523-6b8905ed-bc26-4494-8944-5cb20411f82a.png)

And then grabbing the markdown that's created:
`![image](https://user-images.githubusercontent.com/46163555/222925523-6b8905ed-bc26-4494-8944-5cb20411f82a.png)`

and paste it into your readme.md file.  It'll embed the image.

**Comment by xxenoss** [comment]
I added a screenshot in readme page. Thank you.
